insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('63-9532905', 'Hephzibah Bodycombe', '6 Dorton Point');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('97-2074773', 'Lonny Maletratt', '04 Troy Trail');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('34-4339645', 'Garrard Mouser', '65 Summerview Hill');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('64-2281540', 'Kahaleel Stickler', '436 Clyde Gallagher Pass');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('40-7533043', 'Rubin Serraillier', '782 Packers Plaza');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('08-0229816', 'Tabor Di Iorio', '1321 Manitowish Parkway');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('59-2669530', 'Charline Causer', '0 Morningstar Way');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('82-6804913', 'Kelly Tremmel', '817 Glendale Pass');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('62-6278290', 'Aloysia Pawlicki', '6324 8th Way');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('18-4626580', 'Florida Tabor', '786 Banding Lane');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('41-0584370', 'Lurleen Sapson', '31326 Sunfield Crossing');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('27-8483366', 'Gayleen Wallsworth', '9 Namekagon Road');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('70-4485258', 'Tiphany Hainsworth', '56 Buell Way');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('77-7497577', 'Gradeigh Tremmil', '6144 Lakewood Gardens Lane');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('15-6941230', 'Darrelle Eastridge', '72 Northridge Road');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('96-3951068', 'Gerhardt Scheffel', '937 Village Green Terrace');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('24-1561823', 'Cherice Aslett', '8 Village Parkway');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('33-0758524', 'Carlynne Philipp', '8 Lakewood Crossing');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('15-9344160', 'Dannel O''Dowling', '808 Petterle Pass');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('25-7965866', 'Nathanil Winward', '05070 Carioca Road');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('46-1888361', 'Stanly Orbine', '71824 Evergreen Pass');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('06-1274515', 'Sylvia Laste', '4781 Carpenter Point');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('35-3056847', 'Sandi Nyssen', '7036 Vera Alley');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('13-5042849', 'Parnell Bevis', '9558 Jay Alley');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('41-6485917', 'Paulie Petrovykh', '6739 Raven Terrace');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('36-7474392', 'Alon Hlavecek', '30 Milwaukee Drive');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('68-9677593', 'Bree Chinnock', '5 Milwaukee Crossing');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('37-6497639', 'Brenn Klimt', '44 Nancy Avenue');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('74-3123472', 'Josh Mineghelli', '33505 Lien Parkway');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('13-5632354', 'Austine Bernardinelli', '9 Veith Alley');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('21-0453547', 'Pearle Charter', '67870 Sheridan Lane');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('87-8837123', 'Cammy Thackeray', '5 Green Ridge Terrace');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('83-4875762', 'Flemming Galia', '46382 Cambridge Crossing');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('44-3666862', 'Michale Prate', '82620 Ruskin Circle');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('87-2832586', 'Colan Smallpiece', '78908 Columbus Hill');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('04-2031620', 'Rollo Beare', '36 Miller Crossing');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('22-7874629', 'Dominique Askaw', '40 Anthes Pass');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('45-0173830', 'Nowell Borrow', '974 Redwing Point');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('78-8135447', 'Bartram Oxx', '1685 Glendale Trail');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('93-5564039', 'Inge Haruard', '27688 Briar Crest Plaza');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('61-8589967', 'Kelbee Gamage', '73944 Mallory Drive');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('09-0288290', 'Hyacinthie Watt', '9073 Mendota Park');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('03-8273244', 'Norry Kennelly', '37 Spaight Avenue');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('88-7592741', 'Kelsi Seymer', '6065 Eagan Trail');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('75-6186063', 'Odelia McAlees', '83629 Corry Avenue');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('14-2594141', 'Wenda Bodega', '7956 Farmco Trail');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('15-2351865', 'Bernardina Gillies', '29 Moulton Park');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('41-3356994', 'Crichton Scimoni', '502 Straubel Circle');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('59-4302869', 'Moina Anten', '489 2nd Parkway');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('85-7179405', 'Clay Warburton', '03 Becker Drive');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('67-0377802', 'Janice Blare', '378 Becker Parkway');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('18-8997296', 'Avrom Ivanikov', '8002 Leroy Drive');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('97-7226891', 'Creight Londing', '5085 Moulton Point');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('33-0853562', 'Carmel Housego', '956 Holy Cross Road');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('91-4530946', 'Shirline Twiggs', '1 Briar Crest Court');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('90-7406939', 'Penelopa Brimacombe', '8 Dennis Avenue');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('22-2929351', 'Heinrick Rubens', '72 Oriole Court');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('72-0953169', 'Phelia Sprankling', '6331 Boyd Circle');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('21-2428644', 'Murdoch Boyn', '0785 Leroy Lane');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('88-5951939', 'Philomena Clackson', '41 Roxbury Place');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('40-8188000', 'Marcelia Klehn', '464 Logan Crossing');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('29-9248858', 'Leon Leavens', '5421 Crownhardt Alley');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('70-5608353', 'Karleen Shemming', '871 Monica Drive');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('01-1951230', 'Kayley de Lloyd', '617 Calypso Drive');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('33-9063548', 'Mireielle Klais', '006 Cascade Road');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('16-5474705', 'Norine Halbert', '32500 Jana Center');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('23-2130433', 'Lavina Dumbarton', '12256 South Terrace');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('46-0881215', 'Charity Cowtherd', '1431 Havey Drive');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('41-9163531', 'Jens Samart', '70 Maywood Parkway');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('66-1196205', 'Wyn Artrick', '7 Everett Junction');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('87-0840104', 'Bird Kilgallon', '79001 Debs Alley');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('38-0450465', 'Josepha Fidal', '3079 Ridgeway Hill');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('28-5765277', 'Isaak Beamont', '669 Logan Crossing');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('58-9181712', 'Emilie Cassely', '4 Knutson Place');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('86-9145288', 'Carlynne Jiran', '7016 Eagan Point');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('54-7636767', 'Bree Synnot', '6958 Shopko Court');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('22-6824610', 'Henri Bye', '9453 Nobel Avenue');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('50-7238932', 'Jacklyn Moffet', '0 Luster Circle');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('16-4874212', 'Stan Ranger', '24 Crownhardt Circle');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('17-7459797', 'Zilvia Evanson', '73 Fisk Center');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('90-1836560', 'Eleanore Ridings', '077 Becker Road');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('64-5733889', 'Carine Rawlcliffe', '19 Del Sol Lane');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('32-8861890', 'Norbert Eake', '451 Daystar Park');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('94-1389521', 'Tina Soars', '708 Ridge Oak Avenue');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('75-1132746', 'Cally Burford', '25584 Sommers Lane');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('85-4186059', 'Trumann Behnecken', '6 Sage Terrace');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('48-4278812', 'Catharine Frarey', '4454 Victoria Alley');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('54-2393965', 'Kippy Matisse', '6 Clemons Trail');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('38-2445636', 'Zacharie Bartholin', '6615 Hazelcrest Lane');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('97-8912891', 'Nadean Burnapp', '9535 Sugar Court');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('89-0265276', 'Camile Dani', '8 Schurz Pass');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('48-3962962', 'Gonzalo Fontelles', '510 Londonderry Circle');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('73-6851720', 'Claire Greedyer', '44 Oxford Drive');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('82-5007370', 'Dolph Calderonello', '0787 Monterey Pass');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('68-9866422', 'Reilly Lambal', '62538 Mcbride Crossing');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('01-4841577', 'Catrina Melia', '168 Carberry Street');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('35-3217572', 'Denni Thurlbeck', '4914 Sherman Place');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('58-9925253', 'Boote Laidlaw', '2853 Dovetail Lane');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('94-2136289', 'Valera Gatherell', '514 Sunbrook Way');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('69-9517207', 'Cherri O''Leahy', '8136 Bluejay Pass');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('00-1499117', 'Michale Mingotti', '909 Kedzie Point');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('52-5001228', 'Ryon Lias', '40 Farmco Trail');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('22-0384688', 'Mathilde Goodram', '16906 Mcguire Lane');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('78-1773704', 'Stevena Shropsheir', '61 Helena Junction');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('83-8760804', 'Ilse Fairey', '3526 Rieder Parkway');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('63-4004254', 'Jorge Mathivet', '8 Utah Place');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('52-6209716', 'Alane By', '25810 Carioca Road');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('09-6031702', 'Desdemona Ingerfield', '75013 Ilene Drive');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('84-2523095', 'Katerina Prester', '71 Stone Corner Place');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('58-7500329', 'Gallagher Heggison', '9434 Kropf Lane');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('76-4416345', 'Shandra Petit', '5463 Dahle Alley');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('69-9782972', 'Phyllis Zielinski', '2 Debra Parkway');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('34-0379066', 'Marv Rosle', '52 Thierer Lane');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('50-5092826', 'Vivienne Avrahamy', '1348 Maple Street');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('31-2643841', 'Conney DeSousa', '7001 Ridge Oak Place');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('52-9931038', 'Dode Gorman', '26202 Fairfield Hill');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('36-2155489', 'Dino Mettricke', '77 Del Mar Alley');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('10-1352721', 'Nollie Duncan', '1 Thierer Parkway');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('70-7019999', 'Mathe Saltman', '78 Nobel Plaza');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('63-9412486', 'Marney Amberg', '49333 Toban Avenue');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('61-0813944', 'Weider Kalkofen', '2368 Annamark Trail');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('20-4882632', 'Rosmunda Walbrook', '877 Hoffman Street');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('69-8063621', 'Riki Riddles', '02538 Colorado Court');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('00-3451256', 'Pascale Mounfield', '4 Fulton Center');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('82-3822326', 'Marshal Hue', '9887 Center Point');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('63-1470336', 'Clint Keith', '18631 Dexter Trail');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('73-0085691', 'Cyndy Zouch', '8567 Dovetail Lane');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('45-8248611', 'Travus Brognot', '8 Clarendon Park');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('38-0704100', 'Bren Gwyer', '28170 Rutledge Trail');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('20-7662398', 'Rubi Steketee', '0 Logan Place');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('28-0918184', 'Walther Hollindale', '0 Eagle Crest Road');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('23-6883224', 'Robinet Nerney', '59579 Ryan Street');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('98-1858553', 'Anallise Tomkies', '3 1st Place');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('34-3270600', 'Sadie Vickress', '87773 Buena Vista Trail');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('81-7535077', 'Brit Berridge', '827 Donald Point');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('41-2069205', 'Lacee Errichelli', '224 Bonner Road');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('93-7856238', 'Jorgan Dolligon', '3976 Sundown Hill');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('87-0124792', 'Pier O''Looney', '1782 Bartelt Way');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('81-0397164', 'Dorothee Twelve', '147 Laurel Pass');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('89-3641857', 'Aigneis McGann', '2 Dakota Lane');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('40-8682970', 'Whitby Jorg', '141 Warrior Center');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('50-0124492', 'Annabal Karleman', '37781 Ridgeway Street');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('76-7005254', 'Anette Upstone', '3263 Michigan Way');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('77-2587406', 'Arne Wickersham', '7 Knutson Court');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('27-9971729', 'Ulrika Morrish', '386 Brickson Park Terrace');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('27-3517111', 'Barr Kilgrove', '484 Blackbird Drive');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('91-5759147', 'Trumaine Starten', '03304 Shoshone Plaza');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('70-7948462', 'My Crawshay', '3439 Dottie Center');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('54-2096669', 'Thorndike Julyan', '2 Rusk Avenue');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('99-6290553', 'Blondie Pollington', '691 Summit Circle');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('57-6855721', 'Mignon Tamblyn', '308 Bay Street');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('33-7746632', 'Shurlock Seydlitz', '08952 Crescent Oaks Drive');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('03-0856960', 'Claudelle Halfhead', '340 Oak Avenue');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('86-5000296', 'Edita Cicconetti', '02 Arapahoe Parkway');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('38-1695039', 'Dru Jenckes', '6 Florence Parkway');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('51-7018506', 'Katey Casaccia', '6 Laurel Pass');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('87-7902509', 'Kelci Crissil', '18 Summit Hill');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('28-4198132', 'Axe Greatland', '88910 Village Point');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('72-5135748', 'Jase Coupman', '1135 Merrick Hill');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('73-2749937', 'Gillie Long', '30084 Truax Street');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('02-0188581', 'Chuck Keys', '264 Stephen Center');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('82-7316725', 'Babara Baseggio', '94 School Drive');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('17-0839049', 'Giraldo Averill', '543 Prairieview Alley');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('21-6751728', 'Noemi Billson', '34 Talisman Trail');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('31-5190280', 'Zebulen Kippen', '0953 Oakridge Terrace');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('94-9967623', 'Hugh Canto', '0912 Harper Park');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('19-7809912', 'Bern Taylerson', '2 Esker Point');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('89-8365663', 'Den Bottom', '97196 Bluejay Terrace');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('22-0260285', 'Ruthy Zorzi', '6 Anniversary Lane');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('13-9046824', 'Reinwald Phidgin', '395 Columbus Point');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('07-8415955', 'Silvanus Radin', '27 Maryland Point');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('30-9335113', 'Caresa Masden', '682 Hoepker Trail');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('76-7585383', 'Ettie Caville', '56 Anhalt Pass');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('22-1352635', 'Candra Rosenstein', '48914 Onsgard Circle');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('98-5061673', 'Marlyn Rickson', '909 Brown Plaza');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('49-2570157', 'Johannah McDermid', '72508 Troy Pass');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('92-2954440', 'Bobine Pomfrett', '2334 Melrose Circle');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('12-3615716', 'Hadley Gurling', '4511 Golf Course Crossing');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('94-6055285', 'Robers Cottisford', '2 Ridgeway Hill');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('11-2862029', 'Levy Mowen', '1659 Mallard Center');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('53-9032921', 'Tonnie Schiementz', '13270 Prairieview Drive');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('11-3493779', 'Karia Desmond', '516 Weeping Birch Park');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('22-9924971', 'Yalonda Tupper', '467 Laurel Pass');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('36-3078183', 'Rosette Longbottom', '7 Carey Avenue');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('96-1763322', 'Ddene Batkin', '7041 Barnett Alley');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('31-5310137', 'Lida Glidden', '36004 American Alley');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('58-4294934', 'Rodi Cometson', '66455 Sachs Way');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('62-8380438', 'Judy Colbert', '40 Cody Street');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('25-7926031', 'Niels Gley', '43 Anderson Place');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('19-2618952', 'Manon Geany', '5024 Truax Junction');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('98-2233381', 'Sylvan McCart', '3 Scofield Court');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('94-7335706', 'Myrle Burnand', '363 Dayton Parkway');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('47-2863588', 'Mella Gowman', '78 Bunker Hill Park');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('41-6277170', 'Dolf Trittam', '16 Dwight Pass');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('03-4536849', 'Rozele Cazereau', '47 Lake View Street');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('59-2782516', 'Sheree Peplay', '77 Ridge Oak Center');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('10-8203649', 'Marie-jeanne Ellerington', '91 Pankratz Place');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('19-7367590', 'Kippie Purtell', '2 5th Lane');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('78-9311227', 'Jerald Crowcombe', '3 Rockefeller Circle');
insert into Borrower (Borrower_ID, BorrowerName, BorrowerAddress) values ('14-5338928', 'Teodor Skelcher', '211 Harbort Drive');
